### ISSUE TITLE
Empty result from 'sirius-asr-test.sh'

### ISSUE THREAD

**Issue by ghost** [jhauswald/lucida#1]
[problem] When I try to test ASR of sirius application, I have empty result.
  command : $ ./sirius-asr-test.sh ../inputs/questions/what.is.the.speed.of.light.wav
  result :
![sirius asrtest_strangeresult2](https://cloud.githubusercontent.com/assets/13096272/8424206/dda352c2-1f31-11e5-82d9-1aaa4626f54e.PNG)

[my attempt]
1. try again
  result : in two times, I got right result. And I got empty dozens of times.
![sirius asrtest_rightresult](https://cloud.githubusercontent.com/assets/13096272/8424246/8d7c2f0c-1f32-11e5-884b-238b88e88827.PNG)
2. re-install
  result : no work

[my opinion]
  If I installed wrongly, I think the right results never came out.
And there are many questions like this, but no answer or advice.
To study the sirius, which direction do I need to go on?

thanks to read.

**Comment by jhauswald** [comment]
Try using the inputs in `../inputs/real` those work better with the default ASR that's being used in that script (Kaldi)

**Comment by ghost** [comment]
Thanks you for answering.

I tried. and result is empty.
result : 
![sirius asrtest_real_strangeresult](https://cloud.githubusercontent.com/assets/13096272/8424438/5ae33f2e-1f35-11e5-8c25-7acc3c437b8f.PNG)

I remember.
when the script(sirius-asr-test.sh) gave me right result, there was a time gap between A and B
  A : the spot I entered my command in terminal.
  B : the spot terminal showed me the result.

But normally, there is no time gap. And result is empty. 
Is this fact useful to see my situation?

**Comment by jhauswald** [comment]
What does it show on the ASR server side? Is there output 'received input..." or something? if you're not getting anything on the ASR server, then either Kaldi didn't initialize properly or there's another issue.

**Comment by ghost** [comment]
I'm sorry to tell you this fact.
I have only a server on AWS(Amazon Web Service) and no client computer. I thought that I can install sirius on the server and use it in the server.

But your advice tell me 'you need a server and a client both'. right?

Hmm. Is there a way to study the sirius using only a server?, like word or powerpoint.

**Comment by jhauswald** [comment]
you can open both a server and client on AWS, that shouldn't be a problem.

**Comment by ghost** [comment]
Just thanks you.
